### PR TITLE
rgb-matrix.sh: use newer sha1 of github.com/hzeller/rpi-rgb-led-matrix

### PR DESCRIPTION
**Pull request by flavio-fernandes**

### CODE REVIEW

**Comment by ladyada** [comment]
we purposefully stick to one we know works!

**Comment by hzeller** [comment]
This one works as well :)

**Comment by flavio-fernandes** [comment]
> heheh pardon, i meant works exactly the same with the command line switches we use in the guide - i know they've been updated a bit. we can try this hash too if its more recent but still has the same command lines! :)

Yes, I understand and respect your reason @ladyada .  No biggie if it is best to stay on the older commit. The reason I need the newer commit is because @hzeller did an awesome feature of allowing [rotation of the canvas](https://github.com/hzeller/rpi-rgb-led-matrix/commit/86f1d1468373c68e42e0c79a1a60a717bd0c53a5#diff-eed7d89b967cc3c49983115a739e9c60R270). That allows me to position the matrix display in a way that the ribbon cable is long enough to reach my rpi w/out needing an extension.

It looks to me that @hzeller has made the improvements while being backwards compatible, so I'm hoping the impact on the documentation due to the newer commit is minimal to none. I will be [using it heavily](https://github.com/flavio-fernandes/bedclock) and be sure to let you know if something breaks. I plan on getting it to show-an-tell ... eventually. :^)

You -- as in all of you guys -- rock! <3

**Comment by ladyada** [comment]
flavio, the best thing you can to to make it so we can update is to go through the guide and let us know what still works or does not work with the newer version! then we can update the documentation.

**Comment by flavio-fernandes** [comment]
Hello @ladyada and @PaintYourDragon: I installed Raspbian Stretch Lite from scratch on my rpi zero w
and followed the steps documented on [Adafruit RGB Matrix Bonnet for Raspberry Pi](https://learn.adafruit.com/adafruit-rgb-matrix-bonnet-for-raspberry-pi?view=all).
Well, almost all of them; as I needed to pick up the latest commit from [hzeller/rpi-rgb-led-matrix
](https://github.com/hzeller/rpi-rgb-led-matrix). As seen on this PR. :)

It all worked flawlessly well and I see no issues with the doc in the current format.
I also finished my little bedclock project using commit [814b79b](https://github.com/hzeller/rpi-rgb-led-matrix/commit/814b79b5696d32dd1140304b41a1ec0068bb271a). Pics of that can be [seen here](https://www.flickr.com/gp/38447095@N00/705C56). 

Hope this helps.

**Pull request merged**
