### PR TITLE
Updated Blinka installer to at least install the correct packages

### PR DESCRIPTION
**Pull request by makermelissa**
Tested in a venv and this is working correctly. For some reason it still tries to install RPi.GPIO as a dependency (via pip) and then this script promptly uninstalls it now, but that seems to be some weird issue with the Blinka setup script.

cc: @ladyada  for review

### CODE REVIEW

**Review by ladyada — APPROVED** [review]

**Comment by ladyada** [comment]
cc @caternuson @timonsku

**Comment by caternuson** [comment]
Thanks, LGTM.

Tested with a fresh OS install on a Pi5 starting with `2024-10-22-raspios-bookworm-arm64-lite.img.xz` and following guide:
https://learn.adafruit.com/circuitpython-on-raspberrypi-linux/installing-circuitpython-on-raspberry-pi
but using this updated `raspi-blinka.py` and then testing with `blinkatest.py`.

```
(env) pi@raspberrypi:~ $ python3 blinkatest.py 
Hello, blinka!
Digital IO ok!
I2C ok!
SPI ok!
done!
(env) pi@raspberrypi:~ $
```

**Comment by makermelissa** [comment]
I don't currently have access to merge. Could one of you please do so? Thanks.

**Comment by makermelissa** [comment]
Thank you

**Pull request merged**
