### PR TITLE
St7789 redux

### PR DESCRIPTION
**Pull request by ladyada**
without fbflex, we need a kernel module for any st7789 device!

### CODE REVIEW

**Comment by ladyada** [comment]
if you could try this on both the lil 1.13" minipitft and also the 1.3" or 1.5" TFT bonnet/miniPiTFT - it should work on the very latest pios

**Comment by makermelissa** [comment]
I'm not getting anything on the 1.3" TFT Bonnet. Is the driver turning on the backlight?

**Comment by makermelissa** [comment]
Yeah, I turned it on via Blinka and I see the display now.

**Comment by makermelissa** [comment]
Works great on 1.14"

**Comment by makermelissa** [comment]
After looking at the code, the issue appears to be that the 1.3" mini PiTFT uses Pin 22 for the Backlight and the 1.3" Bonnet uses Pin 26 for the backlight. Can we set both pins to high so that it will work on either one?

**Comment by ladyada** [comment]
ok i changed the DTS, please try re-installing

**Comment by makermelissa** [comment]
Ok, will do. :)

**Comment by makermelissa** [comment]
I can't seem to get it working. I updated the branch, removed any generated files from a previous run and am getting the following output:
```
[PITFT] Updating /boot/config.txt...
/boot/overlays/drm-minipitft13.dtbo: Warning (unit_address_vs_reg): /fragment@0/__overlay__/spidev@0: node has a unit name, but no reg property
############# UPGRADING KERNEL ###############
Hit:1 http://archive.raspberrypi.org/debian buster InRelease
Hit:2 http://raspbian.raspberrypi.org/raspbian buster InRelease
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following package was automatically installed and is no longer required:
  rpi-eeprom-images
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
WARNING : Kernel was updated, please reboot now and re-run script!
```

**Comment by ladyada** [comment]
hmm ok ill get one from the shop - i dont seem to have one here to test with, ill look again

**Comment by makermelissa** [comment]
FWIW, I tried this fresh install again because I messed something up when trying to reset it and it installs fine, it just doesn't display anything on the bonnet. The 1.3" Mini PiTFT tested fine with the latest changes.

**Comment by ladyada** [comment]
@makermelissa try now. its hacky but should light up the backlite on the bonnet :P

**Comment by makermelissa** [comment]
One other question. Since the driver folder is separate of the install script, do we need to update instructions in the guides or does/can the installer script wget the driver folder from here if it doesn't already exist?

**Comment by makermelissa** [comment]
I only tested console, so I am going to test the FBCP method as well based on comments in #102.

**Comment by makermelissa** [comment]
I haven't been able to get the FBCP driver to work at all. It's a black screen with the ST7789 (both the 2.0" and 1.3" displays) and it looks odd on the ILI9341:
3B99132B-6575-4E53-8F14-434A1A07B563_1_105_c

**Comment by ladyada** [comment]
fbcp doesnt work with even the older displays anymore?

**Comment by makermelissa** [comment]
Not on the Pi 4 (with 2 HDMI ports). I can see if it works any differently on the Pi 3 with a single HDMI.

**Comment by ladyada** [comment]
ya dya mind? id like to narrow down if its an issue with the pi4, 5.4 or a combo of the two!

**Comment by makermelissa** [comment]
Nope, I don't mind. :)

**Comment by ladyada** [comment]
thanx - particularly on the ili934x - its disconcerting cause it used to work!

**Comment by makermelissa** [comment]
Ok, ILI9341 looks fine on a Pi 3. I'll try the 2.0" display.

**Comment by makermelissa** [comment]
2.0" display is not working at all now, even in console mode. It's like just installing FBCP breaks something. I tried it both with and without HDMI plugged in.

**Comment by makermelissa** [comment]
1.3" isn't working either anymore. Come to think of it, I had a lite image that I tried the console version on, so the different version may also be a factor.

**Comment by ladyada** [comment]
ok well given this at least fixes console mode, it is merged

**Pull request merged**
